version: "3.2"
services:
  postgresql-db:
    container_name: webapi-sample-postgres-db
    command: postgres -c 'max_connections=200'
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "Pa55word!"